---
# tasks file for awsomeweb
- name: Template index.html.sj2 to index.html on target
  template: 
    src: templates/index.html.j2
    dest: /usr/share/nginx/html/index.html
    mode: 0644
  tags:
    - nginx-template
- name: restart nginx
  service:
    name: nginx
    state: restarted
  notify: Check HTTP Service
  tags:
    - always
